### ISSUE TITLE
Page still points to the JKG2AT repo which is no longer used.

### ISSUE THREAD

**Issue by asaliba** [IzODA/izODA.github.io#17]

**Comment by jbostian** [comment]
The original web portal has a pointer to the JKG2AT source portal, which is now stale. This repo has been replaced with a new Jupyterhub repo. Remove the stale link and the section that refers directly to JKG2AT.

Replace this link and section with a pulldown at the top of each page that elevates the ecosystem to the same logical level as Spark, Anaconda, and ODL. This is in anticipation of additional ecosystem infrastructure, like Zeppelin and Livy.

Also, demote the blog from a pulldown on every page of the portal to a simple link from the portal home page. This frees up space in the pulldown area for the new ecosystem tab.
